FROM node:22-alpine AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

FROM base AS builder

# Install build tools required for node-gyp
RUN apk add --no-cache \
        curl \
        python3 \
        make \
        g++ \
    && ln -sf /usr/bin/python3 /usr/bin/python

WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm run build

FROM base

WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prod --frozen-lockfile
COPY --from=builder /app/dist ./dist

EXPOSE 4000
EXPOSE 9229

CMD ["node", "dist/index.js"]
