import { OfferType } from "../db/schemas/offer";
import { attributesToObject } from "./attributes-to-object";

export const orderOffersObject = (offer: OfferType) => {
  const {
    _id,
    id,
    namespace,
    title,
    description,
    offerType,
    effectiveDate,
    creationDate,
    lastModifiedDate,
    isCodeRedemptionOnly,
    keyImages,
    currentPrice,
    seller,
    productSlug,
    urlSlug,
    url,
    tags,
    items,
    customAttributes,
    categories,
    developerDisplayName,
    publisherDisplayName,
    prePurchase,
    releaseDate,
    pcReleaseDate,
    viewableDate,
    countriesBlacklist,
    countriesWhitelist,
    refundType,
  } = offer;

  return {
    _id,
    id,
    namespace,
    title,
    description,
    offerType,
    effectiveDate,
    creationDate,
    lastModifiedDate,
    isCodeRedemptionOnly,
    keyImages,
    currentPrice,
    seller,
    productSlug,
    urlSlug,
    url,
    tags,
    items,
    customAttributes: attributesToObject(customAttributes as any),
    categories,
    developerDisplayName,
    publisherDisplayName,
    prePurchase,
    releaseDate,
    pcReleaseDate,
    viewableDate,
    countriesBlacklist,
    countriesWhitelist,
    refundType,
  };
};
