import type { OfferType } from '@egdata/core.schemas.offers';
import { attributesToObject } from './attributes-to-object.js';

export const orderOffersObject = (offer: OfferType) => {
  const {
    _id,
    id,
    namespace,
    title,
    description,
    offerType,
    effectiveDate,
    creationDate,
    lastModifiedDate,
    isCodeRedemptionOnly,
    keyImages,
    currentPrice,
    seller,
    productSlug,
    urlSlug,
    url,
    tags,
    items,
    customAttributes,
    categories,
    developerDisplayName,
    publisherDisplayName,
    prePurchase,
    releaseDate,
    pcReleaseDate,
    viewableDate,
    countriesBlacklist,
    countriesWhitelist,
    refundType,
  } = offer;

  return {
    _id,
    id,
    namespace,
    title,
    description,
    offerType,
    effectiveDate,
    creationDate,
    lastModifiedDate,
    isCodeRedemptionOnly,
    keyImages,
    currentPrice,
    seller,
    productSlug,
    urlSlug,
    url,
    tags,
    items,
    customAttributes: customAttributes
      ? attributesToObject(customAttributes)
      : undefined,
    categories,
    developerDisplayName,
    publisherDisplayName,
    prePurchase,
    releaseDate,
    pcReleaseDate,
    viewableDate,
    countriesBlacklist,
    countriesWhitelist,
    refundType,
  };
};
